package org.smp.feature.flags.theme

import androidx.compose.ui.graphics.Color

// ── Light scheme — olive green + white ──────────────────────────────────────
val primaryLight = Color(0xFF55671E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD7E8A3)
val onPrimaryContainerLight = Color(0xFF182100)

val secondaryLight = Color(0xFF8A6D1D)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF3DFA1)
val onSecondaryContainerLight = Color(0xFF2B2000)

val tertiaryLight = Color(0xFF3C6659)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCCE8DD)
val onTertiaryContainerLight = Color(0xFF00201A)

val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)

val backgroundLight = Color(0xFFFFFBF5)
val onBackgroundLight = Color(0xFF1C1C15)
val surfaceLight = Color(0xFFFFFBF5)
val onSurfaceLight = Color(0xFF1C1C15)
val surfaceVariantLight = Color(0xFFE6E2D0)
val onSurfaceVariantLight = Color(0xFF48473A)
val outlineLight = Color(0xFF79765E)
val outlineVariantLight = Color(0xFFCAC6AE)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF31312A)
val inverseOnSurfaceLight = Color(0xFFF4F0E5)
val inversePrimaryLight = Color(0xFFB9D080)
val surfaceDimLight = Color(0xFFE0DCCF)
val surfaceBrightLight = Color(0xFFFFFBF5)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFAF5E9)
val surfaceContainerLight = Color(0xFFF4EFE3)
val surfaceContainerHighLight = Color(0xFFEEEADD)
val surfaceContainerHighestLight = Color(0xFFE8E4D7)

// ── Dark scheme — olive green + white ───────────────────────────────────────
val primaryDark = Color(0xFFB9D080)
val onPrimaryDark = Color(0xFF283500)
val primaryContainerDark = Color(0xFF3D4B08)
val onPrimaryContainerDark = Color(0xFFD7E8A3)

val secondaryDark = Color(0xFFD9C171)
val onSecondaryDark = Color(0xFF3D2E00)
val secondaryContainerDark = Color(0xFF574300)
val onSecondaryContainerDark = Color(0xFFF3DFA1)

val tertiaryDark = Color(0xFFA0D0C0)
val onTertiaryDark = Color(0xFF05372C)
val tertiaryContainerDark = Color(0xFF204E42)
val onTertiaryContainerDark = Color(0xFFCCE8DD)

val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)

val backgroundDark = Color(0xFF15150F)
val onBackgroundDark = Color(0xFFE6E2D5)
val surfaceDark = Color(0xFF15150F)
val onSurfaceDark = Color(0xFFE6E2D5)
val surfaceVariantDark = Color(0xFF48473A)
val onSurfaceVariantDark = Color(0xFFCAC6AE)
val outlineDark = Color(0xFF938F78)
val outlineVariantDark = Color(0xFF48473A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6E2D5)
val inverseOnSurfaceDark = Color(0xFF31312A)
val inversePrimaryDark = Color(0xFF55671E)
val surfaceDimDark = Color(0xFF15150F)
val surfaceBrightDark = Color(0xFF3A3A32)
val surfaceContainerLowestDark = Color(0xFF0F0F0A)
val surfaceContainerLowDark = Color(0xFF1C1C15)
val surfaceContainerDark = Color(0xFF202019)
val surfaceContainerHighDark = Color(0xFF2B2B23)
val surfaceContainerHighestDark = Color(0xFF36362D)
