package org.smp.flagmaster.ui.theme

import androidx.compose.ui.graphics.Color

// ── Light scheme ────────────────────────────────────────────────────────────
val primaryLight = Color(0xFF4355B9)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDDE1FF)
val onPrimaryContainerLight = Color(0xFF00116B)

val secondaryLight = Color(0xFF5B5D72)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDFE0F9)
val onSecondaryContainerLight = Color(0xFF181A2C)

val tertiaryLight = Color(0xFF77536D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD6F3)
val onTertiaryContainerLight = Color(0xFF2D1228)

val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)

val backgroundLight = Color(0xFFFAFAFF)
val onBackgroundLight = Color(0xFF1B1B21)
val surfaceLight = Color(0xFFFAFAFF)
val onSurfaceLight = Color(0xFF1B1B21)
val surfaceVariantLight = Color(0xFFE4E1EC)
val onSurfaceVariantLight = Color(0xFF46464F)
val outlineLight = Color(0xFF777680)
val outlineVariantLight = Color(0xFFC8C5D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303036)
val inverseOnSurfaceLight = Color(0xFFF2EFF7)
val inversePrimaryLight = Color(0xFFBBC2FF)
val surfaceDimLight = Color(0xFFDBD9E0)
val surfaceBrightLight = Color(0xFFFAFAFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F2FA)
val surfaceContainerLight = Color(0xFFEFECF4)
val surfaceContainerHighLight = Color(0xFFE9E7EF)
val surfaceContainerHighestLight = Color(0xFFE3E1E9)

// ── Dark scheme ──────────────────────────────────────────────────────────────
val primaryDark = Color(0xFFBBC2FF)
val onPrimaryDark = Color(0xFF12258E)
val primaryContainerDark = Color(0xFF2B3AA0)
val onPrimaryContainerDark = Color(0xFFDDE1FF)

val secondaryDark = Color(0xFFC2C3DD)
val onSecondaryDark = Color(0xFF2C2E42)
val secondaryContainerDark = Color(0xFF434559)
val onSecondaryContainerDark = Color(0xFFDFE0F9)

val tertiaryDark = Color(0xFFE5B9D8)
val onTertiaryDark = Color(0xFF44263E)
val tertiaryContainerDark = Color(0xFF5D3D55)
val onTertiaryContainerDark = Color(0xFFFFD6F3)

val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)

val backgroundDark = Color(0xFF131318)
val onBackgroundDark = Color(0xFFE4E1E9)
val surfaceDark = Color(0xFF131318)
val onSurfaceDark = Color(0xFFE4E1E9)
val surfaceVariantDark = Color(0xFF46464F)
val onSurfaceVariantDark = Color(0xFFC8C5D0)
val outlineDark = Color(0xFF918F9A)
val outlineVariantDark = Color(0xFF46464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E1E9)
val inverseOnSurfaceDark = Color(0xFF303036)
val inversePrimaryDark = Color(0xFF4355B9)
val surfaceDimDark = Color(0xFF131318)
val surfaceBrightDark = Color(0xFF39373F)
val surfaceContainerLowestDark = Color(0xFF0E0E13)
val surfaceContainerLowDark = Color(0xFF1B1B21)
val surfaceContainerDark = Color(0xFF1F1F26)
val surfaceContainerHighDark = Color(0xFF2A2930)
val surfaceContainerHighestDark = Color(0xFF35333B)
